### ISSUE TITLE
Upgrade client-go and controller-runtime libraries

### ISSUE THREAD

**Issue by masayag** [project-flotta/flotta-operator#153]
In order to move to latest libraries, go version needs to be updated as well to 1.17.

- controller-runtime [changes](https://github.com/kubernetes-sigs/controller-runtime/releases/v0.11.0)

**Comment by ahmadateya** [comment]
I have updated the go.mod file with 1.17 and removed the vendor directory to make sure it will use the new version.

running `go mod tidy` and `go mod vendor` updates the go.mod file with some new packages and edits other packages which mad some updates in the vendor directory, and running `make install` gives some warning about the deprecation of `go get` command but it works.

Now I tested the edits with `make install` and `make uninstall` commands but I am not sure if this upgrade may cause another issue because I am new to the flotta-operator and the project, So would you tell me how to test this upgrade?

this is my PR #172
